# Generated by Django 2.1.3 on 2018-12-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
