from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from django.http import HttpResponse
from django.template import loader


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def index(request):
    template = loader.get_template('blog/index.html')
    context = {
        'latest_question_list': "test",
    }
    return HttpResponse(template.render(context, request))

def A(request): return render(request, 'blog/A.html', {})
def AA(request): return render(request, 'blog/AA.html', {})
def AABA(request): return render(request, 'blog/AABA.html', {})
def AAC(request): return render(request, 'blog/AAC.html', {})
def AAL(request): return render(request, 'blog/AAL.html', {})
def AAN(request): return render(request, 'blog/AAN.html', {})
def AAOI(request): return render(request, 'blog/AAOI.html', {})
def AAON(request): return render(request, 'blog/AAON.html', {})
def AAP(request): return render(request, 'blog/AAP.html', {})
def AAPL(request): return render(request, 'blog/AAPL.html', {})
def AAWW(request): return render(request, 'blog/AAWW.html', {})
def AAXN(request): return render(request, 'blog/AAXN.html', {})
def ABAC(request): return render(request, 'blog/ABAC.html', {})
def ABBV(request): return render(request, 'blog/ABBV.html', {})
def ABC(request): return render(request, 'blog/ABC.html', {})
def ABCD(request): return render(request, 'blog/ABCD.html', {})
def ABEO(request): return render(request, 'blog/ABEO.html', {})
def ABG(request): return render(request, 'blog/ABG.html', {})
def ABIO(request): return render(request, 'blog/ABIO.html', {})
def ABM(request): return render(request, 'blog/ABM.html', {})
def ABMC(request): return render(request, 'blog/ABMC.html', {})
def ABMD(request): return render(request, 'blog/ABMD.html', {})
def ABT(request): return render(request, 'blog/ABT.html', {})
def ACAD(request): return render(request, 'blog/ACAD.html', {})
def ACCO(request): return render(request, 'blog/ACCO.html', {})
def ACER(request): return render(request, 'blog/ACER.html', {})
def ACET(request): return render(request, 'blog/ACET.html', {})
def ACHC(request): return render(request, 'blog/ACHC.html', {})
def ACHN(request): return render(request, 'blog/ACHN.html', {})
def ACHV(request): return render(request, 'blog/ACHV.html', {})
def ACIA(request): return render(request, 'blog/ACIA.html', {})
def ACIW(request): return render(request, 'blog/ACIW.html', {})
def ACLS(request): return render(request, 'blog/ACLS.html', {})
def ACM(request): return render(request, 'blog/ACM.html', {})
def ACN(request): return render(request, 'blog/ACN.html', {})
def ACOR(request): return render(request, 'blog/ACOR.html', {})
def ACRS(request): return render(request, 'blog/ACRS.html', {})
def ACRX(request): return render(request, 'blog/ACRX.html', {})
def ACTG(request): return render(request, 'blog/ACTG.html', {})
def ACU(request): return render(request, 'blog/ACU.html', {})
def ACUR(request): return render(request, 'blog/ACUR.html', {})
def ACXM(request): return render(request, 'blog/ACXM.html', {})
def ACY(request): return render(request, 'blog/ACY.html', {})
def ADBE(request): return render(request, 'blog/ADBE.html', {})
def ADES(request): return render(request, 'blog/ADES.html', {})
def ADI(request): return render(request, 'blog/ADI.html', {})
def ADM(request): return render(request, 'blog/ADM.html', {})
def ADMA(request): return render(request, 'blog/ADMA.html', {})
def ADMP(request): return render(request, 'blog/ADMP.html', {})
def ADMS(request): return render(request, 'blog/ADMS.html', {})
def ADNT(request): return render(request, 'blog/ADNT.html', {})
def ADP(request): return render(request, 'blog/ADP.html', {})
def ADRO(request): return render(request, 'blog/ADRO.html', {})
def ADS(request): return render(request, 'blog/ADS.html', {})
def ADSK(request): return render(request, 'blog/ADSK.html', {})
def ADSW(request): return render(request, 'blog/ADSW.html', {})
def ADTN(request): return render(request, 'blog/ADTN.html', {})
def ADUS(request): return render(request, 'blog/ADUS.html', {})
def ADVM(request): return render(request, 'blog/ADVM.html', {})
def ADXS(request): return render(request, 'blog/ADXS.html', {})
def AE(request): return render(request, 'blog/AE.html', {})
def AEE(request): return render(request, 'blog/AEE.html', {})
def AEGN(request): return render(request, 'blog/AEGN.html', {})
def AEHR(request): return render(request, 'blog/AEHR.html', {})
def AEIS(request): return render(request, 'blog/AEIS.html', {})
def AEMD(request): return render(request, 'blog/AEMD.html', {})
def AEO(request): return render(request, 'blog/AEO.html', {})
def AEP(request): return render(request, 'blog/AEP.html', {})
def AERI(request): return render(request, 'blog/AERI.html', {})
def AES(request): return render(request, 'blog/AES.html', {})
def AET(request): return render(request, 'blog/AET.html', {})
def AETI(request): return render(request, 'blog/AETI.html', {})
def AEY(request): return render(request, 'blog/AEY.html', {})
def AFI(request): return render(request, 'blog/AFI.html', {})
def AGCO(request): return render(request, 'blog/AGCO.html', {})
def AGEN(request): return render(request, 'blog/AGEN.html', {})
def AGFS(request): return render(request, 'blog/AGFS.html', {})
def AGIO(request): return render(request, 'blog/AGIO.html', {})
def AGLE(request): return render(request, 'blog/AGLE.html', {})
def AGN(request): return render(request, 'blog/AGN.html', {})
def AGR(request): return render(request, 'blog/AGR.html', {})
def AGRX(request): return render(request, 'blog/AGRX.html', {})
def AGTC(request): return render(request, 'blog/AGTC.html', {})
def AGX(request): return render(request, 'blog/AGX.html', {})
def AGYS(request): return render(request, 'blog/AGYS.html', {})
def AHC(request): return render(request, 'blog/AHC.html', {})
def AHPA(request): return render(request, 'blog/AHPA.html', {})
def AHPI(request): return render(request, 'blog/AHPI.html', {})
def AIMC(request): return render(request, 'blog/AIMC.html', {})
def AIMT(request): return render(request, 'blog/AIMT.html', {})
def AIN(request): return render(request, 'blog/AIN.html', {})
def AIPT(request): return render(request, 'blog/AIPT.html', {})
def AIR(request): return render(request, 'blog/AIR.html', {})
def AIRG(request): return render(request, 'blog/AIRG.html', {})
def AIRI(request): return render(request, 'blog/AIRI.html', {})
def AIRT(request): return render(request, 'blog/AIRT.html', {})
def AIT(request): return render(request, 'blog/AIT.html', {})
def AJRD(request): return render(request, 'blog/AJRD.html', {})
def AKAM(request): return render(request, 'blog/AKAM.html', {})
def AKAO(request): return render(request, 'blog/AKAO.html', {})
def AKBA(request): return render(request, 'blog/AKBA.html', {})
def AKCA(request): return render(request, 'blog/AKCA.html', {})
def AKER(request): return render(request, 'blog/AKER.html', {})
def AKRX(request): return render(request, 'blog/AKRX.html', {})
def AKS(request): return render(request, 'blog/AKS.html', {})
def AKTS(request): return render(request, 'blog/AKTS.html', {})
def AL(request): return render(request, 'blog/AL.html', {})
def ALAN(request): return render(request, 'blog/ALAN.html', {})
def ALB(request): return render(request, 'blog/ALB.html', {})
def ALBO(request): return render(request, 'blog/ALBO.html', {})
def ALCO(request): return render(request, 'blog/ALCO.html', {})
def ALDR(request): return render(request, 'blog/ALDR.html', {})
def ALDX(request): return render(request, 'blog/ALDX.html', {})
def ALE(request): return render(request, 'blog/ALE.html', {})
def ALG(request): return render(request, 'blog/ALG.html', {})
def ALGN(request): return render(request, 'blog/ALGN.html', {})
def ALGT(request): return render(request, 'blog/ALGT.html', {})
def ALIM(request): return render(request, 'blog/ALIM.html', {})
def ALJJ(request): return render(request, 'blog/ALJJ.html', {})
def ALK(request): return render(request, 'blog/ALK.html', {})
def ALKS(request): return render(request, 'blog/ALKS.html', {})
def ALLE(request): return render(request, 'blog/ALLE.html', {})
def ALNY(request): return render(request, 'blog/ALNY.html', {})
def ALOT(request): return render(request, 'blog/ALOT.html', {})
def ALPN(request): return render(request, 'blog/ALPN.html', {})
def ALQA(request): return render(request, 'blog/ALQA.html', {})
def ALRM(request): return render(request, 'blog/ALRM.html', {})
def ALSK(request): return render(request, 'blog/ALSK.html', {})
def ALSN(request): return render(request, 'blog/ALSN.html', {})
def ALT(request): return render(request, 'blog/ALT.html', {})
def ALV(request): return render(request, 'blog/ALV.html', {})
def ALXN(request): return render(request, 'blog/ALXN.html', {})
def AMAG(request): return render(request, 'blog/AMAG.html', {})
def AMAT(request): return render(request, 'blog/AMAT.html', {})
def AMBA(request): return render(request, 'blog/AMBA.html', {})
def AMBR(request): return render(request, 'blog/AMBR.html', {})
def AMC(request): return render(request, 'blog/AMC.html', {})
def AMCX(request): return render(request, 'blog/AMCX.html', {})
def AMD(request): return render(request, 'blog/AMD.html', {})
